### ISSUE TITLE
Web基礎 前期期末課題 講評

### ISSUE THREAD

**Issue by wangchangdog** [Shieru-ktc/about-me#2]
## Good: 

1年生の前期の時点でNext.jsで課題制作されているのは初めてです。
1年生前期の段階での期待しているレベルを大きく超えていて、今さらながら驚いています。

TypeScript, React, Next.jsを使ってフロントエンド実装ができているので、次はNext.jsのバックエンド実装（BFF）やAPI実装とフロントでのAPI Fetchを伴う本格的なアプリケーション開発にチャレンジされるといいかと思います。
RestAPIの設計、DB設計など難しい点もありそうですがチャレンジ是非チャレンジしてほしいです。

一部を除いて、コミットメッセージも適切に書くことができており、素晴らしいの一言です！

## More:  

強いていうなら、パフォーマンスの最適化の面でやや甘い箇所があります。
具体的にいうと、コンテンツ画像のサイズが大きすぎる場合があります。
目安としては300kb以下にするといいと思います。

以下二つに関しては少し大きすぎるかと思います。
https://github.com/Shieru-ktc/about-me/blob/master/public/osu3.png
https://github.com/Shieru-ktc/about-me/blob/master/public/osu4.png

**Comment by Shieru-ktc** [comment]
![image](https://github.com/user-attachments/assets/2a44d26d-ef85-41f7-9ff4-34252af7380c)

画像サイズって、Next.jsの`Image`コンポーネントを用いれば自動で最適化がかかると思うんですがどうでしょうか
（まあ、それだとしてもサイズは小さくすべきかもしれませんが）

> The Next.js Image component extends the HTML <img> element with features for automatic image optimization:
> 
> Size Optimization: Automatically serve correctly sized images for each device, using modern image formats like WebP and AVIF.
> Visual Stability: Prevent [layout shift](https://nextjs.org/learn/seo/web-performance/cls) automatically when images are loading.
> Faster Page Loads: Images are only loaded when they enter the viewport using native browser lazy loading, with optional blur-up placeholders.
> Asset Flexibility: On-demand image resizing, even for images stored on remote servers

https://nextjs.org/docs/pages/building-your-application/optimizing/images

**Comment by Shieru-ktc** [comment]
というかそもそもそのへんの画像ってunusedでしたね…
